spring.application.name=service-proveedor
server.port=9009

# Base de datos propia para este servicio
spring.datasource.url=jdbc:mysql://localhost:3306/db_proveedor?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Swagger/OpenAPI
springdoc.api-docs.path=/api/v1/proveedores/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.webjars.prefix=/api/v1/proveedores
springdoc.use-management-port=false
springdoc.show-actuator=false
springdoc.hateoas.enabled=false
springdoc.cache.disabled=true

# Forward headers (para Gateway)
server.forward-headers-strategy=framework
server.tomcat.remote-ip-header=x-forwarded-for
server.tomcat.protocol-header=x-forwarded-proto
server.tomcat.port-header=x-forwarded-port

# Evita que Spring Boot intente usar HAL como JSON por defecto
spring.hateoas.use-hal-as-default-json-media-type=false