spring.application.name=service-vehiculo
server.port=9001

spring.datasource.url=jdbc:mysql://localhost:3306/db_vehiculos?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

