spring.application.name=service-ventas
server.port=9004

spring.datasource.url=jdbc:mysql://localhost:3306/db_venta?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true